UCB_C = 1.4
PUCT_C = 1.25

NUM_SEARCHES = 100


# Network Parameters
NUM_CHANNELS = 128
NUM_RES_BLOCKS = 10
POLICY_HEAD_CHANNELS = 2 
VALUE_HEAD_CHANNELS = 1
ACTION_SIZE = 4672

# Dirichlet Noise Parameters
DIRICHLET_ALPHA = 0.3 
DIRICHLET_EPSILON = 0.25

# Training parameters 

TRAIN_ITERATIONS = 75
SELF_PLAY_ITERATIONS = 20
NUM_EPOCHES = 5
BATCH_SIZE = 64
LEARNING_RATE = 0.02

MAX_GAME_LENGTH = 125
TEMPERATURE_MOVES = 15