UCB_C = 1.4
PUCT_C = 1.0

NUM_SEARCHES = 200


# Network Parameters
NUM_CHANNELS = 128
NUM_RES_BLOCKS = 10
POLICY_HEAD_CHANNELS = 2 
VALUE_HEAD_CHANNELS = 1
ACTION_SIZE = 4672

# Dirichlet Noise Parameters
DIRICHLET_ALPHA = 0.3 
DIRICHLET_EPSILON = 0.25

# Training parameters 

TRAIN_ITERATIONS = 125
SELF_PLAY_ITERATIONS = 50
NUM_EPOCHES = 10
BATCH_SIZE = 64
LEARNING_RATE = 0.05